# "dev" conda envs are to be used by devs in setting their local environments
name: pymc
channels:
  - conda-forge
  - defaults
dependencies:
  - pymc>=4.0.0
  - blas
  - cachetools>=4.2.1
  - cloudpickle
  - fastprogress>=0.2.0
  - h5py>=2.7
  - ipython>=7.16
  - jax
  - jupyterlab
  - numpy>=1.15.0
  - numpydoc
  - pandas>=0.24.0
  - pip
  - python-graphviz
  - scipy>=1.4.1
  - typing-extensions>=3.7.4
  - watermark
  - libblas
  - mkl-service
  - pip:
      - polyagamma
